FROM docker.io/library/golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /server ./cmd/server

FROM docker.io/library/alpine:latest

COPY --from=builder /server /server

EXPOSE 10127

CMD ["/server"]
